kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-sonar-data
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/sonarqube/data/
