kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-postgresql
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/
    