apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - image: sonarqube:7.1
          resources:
            limits:
               memory: "2600Mi"
               cpu: 1
            requests:
               cpu: 1
               memory: "2500Mi"
          volumeMounts:
          - mountPath: "/opt/sonarqube/data/"
            name: sonar-data
          - mountPath: "/opt/sonarqube/extensions/"
            name: sonar-extensions
          args:
            - -Dsonar.web.context=/sonar
          name: sonarqube
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-postgres:5432/sonar
          ports:
            - containerPort: 9000
              name: sonarqube
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonar-extensions

#      nodeSelector:
#       nodename: un

#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: sonar-service
#spec:
#  selector:
#    app: sonarqube
#  ports:
#  - port: 80
#    targetPort: 9000
#    name: sonarport
#apiVersion: v1
#kind: Service
#metadata:
#  name: sonar
#spec:
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 9000
#      name: sonarport
#  selector:
#    name: sonarqube
#  type: LoadBalancer
