- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: MC_delivery_westeurope_AKSTEST_Dev
    location: westeurope
    aks_name: Standard_AKSTEST
    username: azureuser
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy4jOx4cY6aL6VKPQbvaIkBExsJoWlWe5xObZRdxtPvEis1z7RDttAljBzEnne2LGNv9MRM21T+OOFjZrx+ySnwbAn6i1A8TCP6LT8wvF1E9wROLDqd7FKGlfECOG77r8dFXGWppLLZrKt6N0Wu+zYCcqWxMwWKVmHGeBp3zGkh7X/8k5lkzJAEesFDS8Sh9T80jJ5goby/jnsiLyjjlQn+UFf3KZnDJJ0RsK5m2UG2qJTGwiWffFEaOBNG3b9j0xQqGBsPyqGSx7td0tcsPtS4IOh6JCofe6FwD2bIQD98rhxybcmk8K3QTgJ7eZPN5HSCOCEFdSOp10+BYs8pRA9 jenkins@jenkins-ansible-Machine

    client_id: 1223412302
    client_secret: ;>poezrtpo
  tasks:
  - name: Create a managed Azure Container Services (AKS) cluster
    azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      linux_profile:
        admin_username: "{{ username }}"
        ssh_key: "{{ ssh_key }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: default
          count: 2
          vm_size: Standard_D2_v2
      tags:
        Environment: Dev

