- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: MC_delivery_westeurope_aaa_Dev
    location: westeurope
    aks_name: aaa
    username: azureuser
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/2pEbh3ZwbM2VNj4+UdYN9FqGLnuvAnpEmIf25LzC+50vrw4e59hT5+jjCBtxFhDk5AMveFjiY3kHCw7zA8Dq1W60THxNZd6mwgFWbKH1LE6lxS3+INMUQrkzd4s8rEfajdgqIltC3Zjq0khTTT6a8aYnPBYXXo7c2Tr3KVYUGgWF2kLeIFOT+dQZLeoyz80DCMZzMoiExMOpxPprA9DAz5maN9O3SvWME+NTlMb6+AceTZ4VnHz2/Ha2pCaXzh43IS3ZqaKI1kjyDHI9cLl+BZ/Ld3CVIunMZvrvD76O+1KMnJBcWyX26iI/plK9WC3Qy9aQNM5jBwvX+BNrSj+7 t.sdiri@quartetfs@LP023
    client_id: 1223412302
    client_secret: ;>poezrtpo
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create a managed Azure Container Services (AKS) cluster
    azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      linux_profile:
        admin_username: "{{ username }}"
        ssh_key: "{{ ssh_key }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: default
          count: 1
          vm_size: Standard_DS1_v2
      tags:
        Environment: Dev
