- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: a_Dev
    location: westeurope
    username: azureuser
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/2pEbh3ZwbM2VNj4+UdYN9FqGLnuvAnpEmIf25LzC+50vrw4e59hT5+jjCBtxFhDk5AMveFjiY3kHCw7zA8Dq1W60THxNZd6mwgFWbKH1LE6lxS3+INMUQrkzd4s8rEfajdgqIltC3Zjq0khTTT6a8aYnPBYXXo7c2Tr3KVYUGgWF2kLeIFOT+dQZLeoyz80DCMZzMoiExMOpxPprA9DAz5maN9O3SvWME+NTlMb6+AceTZ4VnHz2/Ha2pCaXzh43IS3ZqaKI1kjyDHI9cLl+BZ/Ld3CVIunMZvrvD76O+1KMnJBcWyX26iI/plK9WC3Qy9aQNM5jBwvX+BNrSj+7 t.sdiri@quartetfs@LP023
    client_id: a084bea2-4c58-486f-a9a1-631af5454943
    client_secret: 4/lpor8MU*pnxjJGkyt+LWM-VtC9w9Sr
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"