apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keyckloak-data
  annotations: 
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi