apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  annotations: 
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi