kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jenkins-slave
  annotations:
    pv.beta.kubernetes.io/gid: "10000"
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: claim-jenkins-slave
  hostPath:
    path: /home/jenkins/.m2/
