- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: testmardisixDev
    location: westeurope
    username: azureuser
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy4jOx4cY6aL6VKPQbvaIkBExsJoWlWe5xObZRdxtPvEis1z7RDttAljBzEnne2LGNv9MRM21T+OOFjZrx+ySnwbAn6i1A8TCP6LT8wvF1E9wROLDqd7FKGlfECOG77r8dFXGWppLLZrKt6N0Wu+zYCcqWxMwWKVmHGeBp3zGkh7X/8k5lkzJAEesFDS8Sh9T80jJ5goby/jnsiLyjjlQn+UFf3KZnDJJ0RsK5m2UG2qJTGwiWffFEaOBNG3b9j0xQqGBsPyqGSx7td0tcsPtS4IOh6JCofe6FwD2bIQD98rhxybcmk8K3QTgJ7eZPN5HSCOCEFdSOp10+BYs8pRA9 jenkins@jenkins-ansible-Machine

    client_id: a084bea2-4c58-486f-a9a1-631af5454943
    client_secret: 4/lpor8MU*pnxjJGkyt+LWM-VtC9w9Sr
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"