- name: Create (or update) SQL Server
  hosts: localhost
  connection: local
  tasks:
  - name: Create SQL Server
    azure_rm_sqlserver:
     resource_group: resource_group_value
     name: db_server_name
     location: location_value
     admin_username: admin_user_name
     admin_password: admin_pwd
