- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: resource_group_value
    location: westeurope
    username: azureuser
    ssh_key: ssh-rsa_value
    client_id: client_id_value
    client_secret: client_secret_value
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"